apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp
  namespace: nodejs
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asp
      tier: backend
  template:
    metadata:
      labels:
        app: asp
        tier: backend
    spec:
      containers:
      - name: asp
        image: 256611426845.dkr.ecr.ap-south-1.amazonaws.com/nodejs:latest
        ports:
        - containerPort: 8080