apiVersion: v1
kind: Service
metadata:
  name: asp
  namespace: nodejs
  labels:
    tier: backend
spec:
  selector:
    app: asp
    tier: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080