

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::256611426845:role/eksctl-sushan-test-nodegroup-ng-b-NodeInstanceRole-28Q03A1Q3O9V
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::042002498327:role/prod-tf-codebuild-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::256611426845:user/pawan
      username: pawan
      groups:
        - system:masters
    - userarn: arn:aws:iam::256611426845:user/sushan1
      username: sushan1
      groups:
        - system:manager
